config/routes.rb
Rails.application.routes.draw do
  resources :musicalinstruments
  resources :countries
  resources :cities
  root 'welcome#index'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/musicalinstrument.rb
class Musicalinstrument < ApplicationRecord
end

app/controllers/musicalinstruments_controller.rb
class MusicalinstrumentsController < ApplicationController
  before_action :set_musicalinstrument, only: %i[ show edit update destroy ]

  # GET /musicalinstruments or /musicalinstruments.json
  def index
    @musicalinstruments = Musicalinstrument.all
  end

  # GET /musicalinstruments/1 or /musicalinstruments/1.json
  def show
  end

  # GET /musicalinstruments/new
  def new
    @musicalinstrument = Musicalinstrument.new
  end

  # GET /musicalinstruments/1/edit
  def edit
  end

  # POST /musicalinstruments or /musicalinstruments.json
  def create
    @musicalinstrument = Musicalinstrument.new(musicalinstrument_params)

    respond_to do |format|
      if @musicalinstrument.save
        format.html { redirect_to musicalinstrument_url(@musicalinstrument), notice: "Musicalinstrument was successfully created." }
        format.json { render :show, status: :created, location: @musicalinstrument }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @musicalinstrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musicalinstruments/1 or /musicalinstruments/1.json
  def update
    respond_to do |format|
      if @musicalinstrument.update(musicalinstrument_params)
        format.html { redirect_to musicalinstrument_url(@musicalinstrument), notice: "Musicalinstrument was successfully updated." }
        format.json { render :show, status: :ok, location: @musicalinstrument }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @musicalinstrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicalinstruments/1 or /musicalinstruments/1.json
  def destroy
    @musicalinstrument.destroy!

    respond_to do |format|
      format.html { redirect_to musicalinstruments_url, notice: "Musicalinstrument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musicalinstrument
      @musicalinstrument = Musicalinstrument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def musicalinstrument_params
      params.require(:musicalinstrument).permit(:name)
    end
end

app/helpers/musicalinstruments_helper.rb
module MusicalinstrumentsHelper
end

app/views/musicalinstruments/_form.html.erb
<%= form_with(model: musicalinstrument) do |form| %>
  <% if musicalinstrument.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(musicalinstrument.errors.count, "error") %> prohibited this musicalinstrument from being saved:</h2>

      <ul>
        <% musicalinstrument.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/musicalinstruments/_musicalinstrument.html.erb
<div id="<%= dom_id musicalinstrument %>">
  <p>
    <strong>Name:</strong>
    <%= musicalinstrument.name %>
  </p>

</div>

app/views/musicalinstruments/edit.html.erb
<h1>Editing musicalinstrument</h1>

<%= render "form", musicalinstrument: @musicalinstrument %>

<br>

<div>
  <%= link_to "Show this musicalinstrument", @musicalinstrument %> |
  <%= link_to "Back to musicalinstruments", musicalinstruments_path %>
</div>

app/views/musicalinstruments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Musicalinstruments</h1>

<div id="musicalinstruments">
  <% @musicalinstruments.each do |musicalinstrument| %>
    <%= render musicalinstrument %>
    <p>
      <%= link_to "Show this musicalinstrument", musicalinstrument %>
    </p>
  <% end %>
</div>

<%= link_to "New musicalinstrument", new_musicalinstrument_path %>

app/views/musicalinstruments/new.html.erb
<h1>New musicalinstrument</h1>

<%= render "form", musicalinstrument: @musicalinstrument %>

<br>

<div>
  <%= link_to "Back to musicalinstruments", musicalinstruments_path %>
</div>

app/views/musicalinstruments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @musicalinstrument %>

<div>
  <%= link_to "Edit this musicalinstrument", edit_musicalinstrument_path(@musicalinstrument) %> |
  <%= link_to "Back to musicalinstruments", musicalinstruments_path %>

  <%= button_to "Destroy this musicalinstrument", @musicalinstrument, method: :delete %>
</div>